### ISSUE TITLE
Silent failure when `Cargo.toml` is broken

### ISSUE THREAD

**Issue by bonsairobo** [ForesightMiningSoftwareCorporation/fslabscli#33]
[This PR](https://github.com/ForesightMiningSoftwareCorporation/fsl_libs/pull/902) broke `fsl_widget_collection` with a seemingly innocuous merge of `dev` into the PR branch. There was in fact a `Cargo.toml` conflict that wasn't detected by the merge. This is normally something that should have been detected by CI, but it seems that CI failed silently [here](https://github.com/ForesightMiningSoftwareCorporation/fsl_libs/actions/runs/9667265870/job/26668681572) in the "Check Workspace" step. The `fslabscli` tool crashed because of the very same `Cargo.toml` issue:

```
error: failed to load manifest for workspace member `/var/home/duncan/WorkCode/fsl_libs/aec4d/crates/aec4d_client`

Caused by:
  failed to load manifest for dependency `fsl_widget_collection`

Caused by:
  failed to parse manifest at `/var/home/duncan/WorkCode/fsl_libs/fse_app/crates/fsl_widget_collection/Cargo.toml`

Caused by:
  TOML parse error at line 44, column 1
     |
  44 | nalgebra = { version = "^0.32.2", features = ["convert-glam024"] }
     | ^
  duplicate key `nalgebra` in table `dependencies`
```

Because this workflow was also generated by the CLI, I think the blame lays in this repo. Let me know if you disagree.

I can't hazard a guess at the root cause. Somehow the step that invokes the CLI is not detecting failure and propagating that to the final CI report (which appears completely empty in that PR).

@Makogan I think you should be careful not to merge when you see the CI report completely empty instead of containing the expected :heavy_check_mark:s on the expected crates.

**Comment by loispostula** [comment]
@bonsairobo thanks for this finding, I think indeed the blame lays in part here. I think i'm going to make a big try catch in this tool and report when it fails. That way I can change the `Test result summary`to take that into account and not silently fail
